package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AllianceBackup alliance backup
// swagger:model AllianceBackup
type AllianceBackup struct {

	// Team key of incoming team
	// Required: true
	In *string `json:"in"`

	// Team key of outgoing team
	// Required: true
	Out *string `json:"out"`
}

// Validate validates this alliance backup
func (m *AllianceBackup) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIn(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateOut(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AllianceBackup) validateIn(formats strfmt.Registry) error {

	if err := validate.Required("in", "body", m.In); err != nil {
		return err
	}

	return nil
}

func (m *AllianceBackup) validateOut(formats strfmt.Registry) error {

	if err := validate.Required("out", "body", m.Out); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AllianceBackup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AllianceBackup) UnmarshalBinary(b []byte) error {
	var res AllianceBackup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
