package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RankingSortOrder ranking sort order
// swagger:model RankingSortOrder
type RankingSortOrder struct {

	// Description of this ranking column
	// Required: true
	Name *string `json:"name"`

	// How many significant figures to display
	// Required: true
	Precision *int64 `json:"precision"`
}

// Validate validates this ranking sort order
func (m *RankingSortOrder) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validatePrecision(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RankingSortOrder) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *RankingSortOrder) validatePrecision(formats strfmt.Registry) error {

	if err := validate.Required("precision", "body", m.Precision); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RankingSortOrder) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RankingSortOrder) UnmarshalBinary(b []byte) error {
	var res RankingSortOrder
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
