package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RankingResponseObject ranking response object
// swagger:model RankingResponseObject
type RankingResponseObject struct {

	// extra stats info
	ExtraStatsInfo []*RankingSortOrder `json:"extra_stats_info"`

	// rankings
	// Required: true
	Rankings []*RankingItem `json:"rankings"`

	// sort order info
	// Required: true
	SortOrderInfo []*RankingSortOrder `json:"sort_order_info"`
}

// Validate validates this ranking response object
func (m *RankingResponseObject) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExtraStatsInfo(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateRankings(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSortOrderInfo(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RankingResponseObject) validateExtraStatsInfo(formats strfmt.Registry) error {

	if swag.IsZero(m.ExtraStatsInfo) { // not required
		return nil
	}

	for i := 0; i < len(m.ExtraStatsInfo); i++ {

		if swag.IsZero(m.ExtraStatsInfo[i]) { // not required
			continue
		}

		if m.ExtraStatsInfo[i] != nil {

			if err := m.ExtraStatsInfo[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("extra_stats_info" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *RankingResponseObject) validateRankings(formats strfmt.Registry) error {

	if err := validate.Required("rankings", "body", m.Rankings); err != nil {
		return err
	}

	for i := 0; i < len(m.Rankings); i++ {

		if swag.IsZero(m.Rankings[i]) { // not required
			continue
		}

		if m.Rankings[i] != nil {

			if err := m.Rankings[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("rankings" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *RankingResponseObject) validateSortOrderInfo(formats strfmt.Registry) error {

	if err := validate.Required("sort_order_info", "body", m.SortOrderInfo); err != nil {
		return err
	}

	for i := 0; i < len(m.SortOrderInfo); i++ {

		if swag.IsZero(m.SortOrderInfo[i]) { // not required
			continue
		}

		if m.SortOrderInfo[i] != nil {

			if err := m.SortOrderInfo[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("sort_order_info" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RankingResponseObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RankingResponseObject) UnmarshalBinary(b []byte) error {
	var res RankingResponseObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
